baseURL = "https://quig.info/blog"
title = "Mike Quigley"
theme = "cactus"
languageCode = "en-US"

publishDir = "docs"

[params]
	description = "Journal for projects, etc."
	mainSection = "posts"
	showAllPostsOnHomePage = true
	css = ["css/custom.css"]
	colortheme = "white"

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "Back to quig.info"
url = "https://quig.info"
weight = 2

[[params.social]]
	name = "github"
	link = "https://github.com/mdquigley"

[[params.social]]
	name = "twitter"
	link = "https://twitter.com/quig_m"

[[params.social]]
	name = "email"
	link = "quig.info@gmail.com"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4